DATASET:
  VIDEOS: ['4K9A0217', '4K9A0218', '4K9A0219', '4K9A0220', '4K9A0221', '5566', '5568', '5570']
MODEL:
  CLIP_LEN: 300
  USE_CAMERA_POSE: False
  MTPGR_CKPT: 'no_spatial_edges.ckpt'
  NO_SPATIAL_EDGES: True 